# Generated by Django 3.0.2 on 2020-03-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('Phone_no', models.CharField(max_length=10)),
                ('Street_add', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=30)),
                ('Zipcode', models.CharField(max_length=6)),
                ('Department', models.CharField(choices=[('Teller', 'Teller'), ('Customer Service', 'Customer Service'), ('Loan Servicing', 'Loan Servicing'), ('Cash Management', 'Cash Management'), ('Electronic Banking', 'Electronic Banking'), ('Mortage Banking', 'Mortage Banking')], max_length=20)),
                ('Salary', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
