# Generated by Django 3.0.2 on 2020-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Image',
            field=models.ImageField(default=4, upload_to='\\Emp_Images'),
            preserve_default=False,
        ),
    ]
