# Generated by Django 3.0.2 on 2020-03-07 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('Phone_no', models.CharField(max_length=10)),
                ('Street_add', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=30)),
                ('Zipcode', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('Ac_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Ac_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=7)),
                ('Start_date', models.DateField()),
                ('Ac_balance', models.BigIntegerField()),
                ('Trans_limit', models.BigIntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer')),
            ],
            options={
                'db_table': 'Accounts',
            },
        ),
    ]
