# Generated by Django 3.0.2 on 2020-06-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customer_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='Customer.Accounts')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='Customer.Accounts')),
            ],
            options={
                'db_table': 'Transfers',
            },
        ),
        migrations.CreateModel(
            name='DepositsWithdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('Account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Accounts')),
            ],
            options={
                'db_table': 'Depositswithdrawals',
            },
        ),
    ]
